package com.euler.solutions.impl;

import java.util.ArrayList;
import java.util.List;

import com.euler.solutions.IntegerSolution;

/*
 * Even Fibonacci numbers
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By
 * starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find
 * the sum of the even-valued terms.
 */

public class Problem002 extends IntegerSolution {
	/*
	 * Naive recursive solution for finding terms in the Fibonacci sequence (for now). Time
	 * complexity is exponential.
	 */
	public static Integer fibonacciRecursive(int seedA, int seedB, int index) {
		if (index < 0) {
			throw new IllegalArgumentException("The index must be a non-negative integer.");
		} else if (index == 0) {
			return seedA;
		} else if (index == 1) {
			return seedB;
		} else {
			return fibonacciRecursive(seedA, seedB, index - 1)
					+ fibonacciRecursive(seedA, seedB, index - 2);
		}
	}

	/*
	 * Memoized solution for finding terms in the Fibonacci sequence. Time complexity is linear.
	 */
	public static Integer fibonacciMemoized(int seedA, int seedB, int index) {
		if (index < 0) {
			throw new IllegalArgumentException("The index must be a non-negative integer.");
		}

		Integer[] terms = new Integer[index + 1];
		terms[0] = seedA;
		terms[1] = seedB;

		for (int i = 2; i < index + 1; i++) {
			terms[i] = terms[i - 1] + terms[i - 2];
		}
		return terms[index];
	}

	public static List<Integer> listOfFibonacciTerms(int seedA, int seedB, int limit) {
		List<Integer> terms = new ArrayList<>();
		Integer max = Math.max(seedA, seedB);

		if (max == limit) {
			terms.add(max);
		}

		if (max < limit) {
			Integer count = 0;
			Integer current = fibonacciRecursive(seedA, seedB, count);
			while (current <= limit) {
				terms.add(current);
			}
		}
		return terms;
	}

	public static Integer sumOfEvenFibonacciTerms(int seedA, int seedB, int limit) {
		List<Integer> terms = listOfFibonacciTerms(seedA, seedB, limit);
		Integer sum = terms.stream().filter(t -> t % 2 == 0).mapToInt(Integer::intValue).sum();
		return sum;
	}

	@Override
	public Integer solution() {
		return sumOfEvenFibonacciTerms(1, 2, 4000000);
	}
}